src/net/vavasoft/servlet/UserRegister.java
=> regex validation

WebContent/app/charge_tab.jsp, WebContent/app/sub04.jsp, WebContent/header.jsp, WebContent/js/additional-methods.js, WebContent/js/jquery.serializejson.js, WebContent/js/jquery.validate.js, WebContent/process/application/charge/getBankAccount.jsp, WebContent/process/application/charge/setChargeApplication.jsp, WebContent/register.jsp, src/net/vavasoft/bean/UserBean.java, src/net/vavasoft/dao/UserDao.java
added charge application, modified header.jsp
=> added charge application, modified header.jsp

WebContent/register.jsp
=> fix register.jsp

WebContent/app/charge_tab.jsp, WebContent/process/login_process.jsp, WebContent/register.jsp, src/net/vavasoft/dao/UserDao.java
=> added login session update

WebContent/app/charge_tab.jsp, WebContent/css/common.css, WebContent/css/common2.css, WebContent/css/nice-select.css, WebContent/header.jsp, WebContent/js/jquery.nice-select.js, WebContent/process/register_process.jsp, WebContent/register.jsp, src/net/vavasoft/dao/UserDao.java
added nice-select, register auto login, money not session
=> added nice-select, register auto login, money not session

WebContent/app/sub04.jsp, WebContent/info/profile.jsp, WebContent/info/sub05.jsp, WebContent/process/info/passwordChecker.jsp, WebContent/process/info/updateProfile.jsp, WebContent/process/info/updateUserPassword.jsp, WebContent/process/session_checker.jsp, src/net/vavasoft/dao/UserDao.java
=> update password and profile

WebContent/info/betting_history.jsp
betting_history datatable test
=> betting_history test

WebContent/app/charge_tab.jsp, WebContent/app/moneyuse_tab.jsp, WebContent/app/point_tab.jsp, WebContent/css/common2.css, WebContent/header.jsp, WebContent/info/betting_history.jsp, WebContent/info/profile.jsp, WebContent/js/accordion.js, WebContent/process/application/charge/getBankAccount.jsp, WebContent/process/application/charge/setChargeApplication.jsp, WebContent/process/application/exchange/getWithdrawList.jsp, WebContent/process/info/passwordChecker.jsp, WebContent/process/info/updateProfile.jsp, WebContent/process/info/updateUserPassword.jsp, WebContent/process/joincode_checker.jsp, WebContent/process/login_process.jsp, WebContent/process/logout_process.jsp, WebContent/process/referrence_checker.jsp, WebContent/process/send_sms.jsp, WebContent/process/session_checker.jsp, WebContent/process/userid_checker.jsp, WebContent/process/verify_cellnum.jsp, WebContent/process/verify_cert_num.jsp, WebContent/register.jsp
change accordion js and css, set to lee coding standard
=> change accordion js and css, set to lee coding standard

WebContent/inc/session.jsp
added DecimalFormat dfrmt2= new DecimalFormat("#,###,###,###,###");
=> fix session

WebContent/account/account.jsp, WebContent/cash/charge_tab.jsp, WebContent/casino/casino.jsp, WebContent/inc/footer.jsp, WebContent/inc/header.jsp, WebContent/info/bet_history.jsp, WebContent/info/contact.jsp, WebContent/info/jsp/delBettingHistory.jsp, WebContent/info/profile.jsp, WebContent/js/popup.js, WebContent/login/jsp/get_header.jsp, WebContent/login/jsp/get_session.jsp, WebContent/login/login.jsp, WebContent/virtual/vgaming.jsp
change account.jsp style
fix bet_history.jsp delete
fix footer
added vgaming casino login no reload
fix profile and charge tooltip
=> fix profile tooltips and style

WebContent/cash/charge_tab.jsp, WebContent/cash/exchange_tab.jsp, WebContent/cash/jsp/setChargeApplication.jsp, WebContent/cash/switch_points.jsp, WebContent/css/common2.css, WebContent/inc/header.jsp, WebContent/index.jsp, WebContent/js/additional-methods.js, WebContent/js/common.js
comma in cash.jsp
button cursors in cash
=> ie logout fix

WebContent/account/account.jsp, WebContent/cash/charge_tab.jsp, WebContent/css/common2.css, WebContent/inc/header.jsp, WebContent/info/contact.jsp, WebContent/info/profile.jsp, WebContent/js/sub_tab.js, WebContent/login/jsp/get_header.jsp, WebContent/login/register.jsp, src/dao/ChargeDao.java
change fadein effect / datatable fix
removed tooltip close button
fix popup menu money comma and logout text
=> fix chargedao date time

WebContent/inc/header.jsp, WebContent/index.jsp, WebContent/login/jsp/get_header.jsp, WebContent/login/login.jsp, WebContent/sport/livematch.jsp, WebContent/sport/prematch.jsp, src/bc4/BetConManager2.java, src/dao/NoticeEventDao.java
added reload on live match and prematch.jsp
=> added popup

WebContent/casino/casino.jsp, WebContent/inc/header.jsp, WebContent/login/login.jsp, WebContent/minigame/list.jsp, WebContent/virtual/vgaming.jsp
=> change popup width height

WebContent/css/common2.css, WebContent/info/bet_history.jsp, src/dao/NoticeEventDao.java
fix calendar bet_history.jsp
change css datatable
=> fix popup select date

WebContent/css/common3.css, WebContent/css/customize.css, WebContent/css/sub.css, WebContent/index.jsp, WebContent/info/bet_history.jsp, WebContent/info/contact.jsp, WebContent/info/info.jsp, WebContent/info/qna.jsp, WebContent/js/lmatch.js, WebContent/js/pmatch.js, WebContent/match/result.jsp, WebContent/sport/center_pre.html, WebContent/sport/right_bet.html, WebContent/sport/top_live29.html, WebContent/sport/top_live3.html, WebContent/sport/top_live4.html, WebContent/sport/top_live5.html, WebContent/sport/top_live6.html, src/dao/QnaDao.java
datatable change css/common2.css
fix load qna datable
fix date qna datatable
fix contact messages
=> server update

WebContent/inc/header.jsp, WebContent/info/info.jsp, WebContent/info/jsp/updateRecvMsg.jsp, WebContent/info/qna.jsp, WebContent/login/jsp/get_header.jsp, WebContent/login/jsp/get_msgcount.jsp, src/dao/MessageDao.java
=> + message counter

WebContent/css/customize.css, WebContent/inc/header.jsp, WebContent/js/lmatch.js, WebContent/js/pmatch.js, WebContent/sport/center_market.html, WebContent/sport/top_live3.html, src/bc4/BetConManager2.java, src/dao/ChargeDao.java
=> + server changes

WebContent/cash/cash.jsp, WebContent/cash/charge_tab.jsp, WebContent/cash/exchange_tab.jsp, WebContent/cash/jsp/getWithdrawList.jsp, WebContent/cash/jsp/switchPoints.jsp, WebContent/cash/switch_points.jsp, WebContent/info/jsp/setMessage.jsp, src/dao/QnaDao.java, src/dao/UserDao.java
=> + server changes cash

WebContent/cash/charge_tab.jsp, WebContent/css/customize.css, WebContent/index.jsp, WebContent/info/bet_history.jsp, WebContent/login/jsp/login_process.jsp, WebContent/login/jsp/register_process.jsp, WebContent/login/register.jsp, src/dao/UserDao.java
=> +server changes
